files:
  include: 'style/*.scss'


rules:
  clean-import-paths:
    - 0
    -
      filename-extension: false
      leading-underscore: false
  property-sort-order:
    - 0
  leading-zero:
    - 0
  class-name-format:
    - 0
  shorthand-values:
    - 0
  zero-unit:
    - 0
  no-ids:
    - 0
  nesting-depth:
    - 2
    -
      max-depth: 4
  mixins-before-declarations:
    - 0
  empty-args:
    - 0
  hex-length:
    - 0
